# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='spoons',
        ),
        migrations.AddField(
            model_name='day',
            name='spoonsnow',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='day',
            name='spoonstart',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
