# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoons', '0002_auto_20171116_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='spoonsnow',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='day',
            name='spoonstart',
            field=models.IntegerField(default=20),
        ),
    ]
